## Configuration Spring
spring:
  ## Configuration de la BD
  datasource:
    url: jdbc:mysql://localhost:3306/db_hauss?useSSL=false&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: Iotr@2024
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  ## Configuration de l'ORM JPA
  jpa:
    database: MYSQL # Le SGBD utilisé
    show-sql: true # Afficher la requête SQL générée par Hibernate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect # Le SGBD Dialect
    hibernate:
      ddl-auto: none #(none, validate, create, create-drop, create-only, update)

  ## Configuration de Flyway
  flyway:
    enabled: true
    locations: classpath:db/migration  # Répertoire des fichiers de migration

  ## Configuration de l'e-mail
  mail:
    host: smtp.gmail.com
    port: 587
    username: dabodabo9064@gmail.com
    password: "xjeq hymh vqke ypuw"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

## Configuration du server
server:
  port: 8081
